/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_palliums_libraclientlib_Account */

#ifndef _Included_com_palliums_libraclientlib_Account
#define _Included_com_palliums_libraclientlib_Account
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_palliums_libraclientlib_Account
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_palliums_libraclientlib_Account_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
